### ISSUE TITLE
hotfix branch: broken compatibility with PHP 5.4 and lower (Cryptor error)

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#2160]
I'm still investigating it, but it seems that if we upgrade existing installations with latest hotfix branch, and which are running on older PHP versions (5.3, 5.4*), search becomes unusable, because of Cryptor library.

Issues: (irrelevant permalinks setting)
* search / location links return **HTTP 500** with the following error:

```
PHP Fatal error:  Uncaught exception 'Exception' with message 'Cryptor:: - unknown cipher algo aes-256-ctr' in oc-includes\openssl-cryptor\Cryptor.php:51
Stack trace:
#0 oc-includes\openssl-cryptor\Cryptor.php(166): Cryptor->__construct()
#1 oc-includes\osclass\helpers\hSecurity.php(281): Cryptor::Encrypt('5DIzqeYpgg7L7ky...', '?Bj??????Luz???...', 0)
#2 oc-includes\osclass\controller\search.php(545): osc_encrypt_alert('{"price_min":0,...')
#3 index.php(102): CWebSearch->doModel()
#4 {main}
  thrown in oc-includes\openssl-cryptor\Cryptor.php on line 51
```

Under PHP 5.3 the error is little different (it depends on version):

`PHP Parse error:  syntax error, unexpected '[' in /oc-includes/openssl-cryptor/Cryptor.php on line 101`

It works fine under 5.4.45, but not in 5.4.1x and 5.4.2x (cannot test every minor version).

Can you verify this issue on your end?
Thanks

**Comment by conejoninja** [comment]
Hi,
we can not verify this on our end, as the only version of 5.4 we could get is 5.4.45 (docker). PHP 5.3, 5.4 and 5.5 should be dead by now, but any way.


Error in PHP 5.3 is due to the shortened array syntax introduced in 5.4 ( http://php.net/manual/en/migration54.new-features.php ) and should be fixed by this : https://github.com/osclass/Osclass/commit/c5a018f9cc53f1932c40e136aff37042964badd7

The exception, is because the default cipher algorithm is not available in the openssl extension. Now, it's configurable with some constant. Probably we could make it configurable, but not sure how frequent this issue is and I don't think it's something a regular admin should be modifying without knowing what is doing.

**Comment by dev-101** [comment]
Hi Conejo, actually, this fixed everything in lower 5.4.x versions, as well (error just manifested differently).

Thanks! :beer:

**Comment by dev-101** [comment]
Unfortunately, I clicked on wrong bookmark (neighbor), and went to a newer test environment (php 5.6), instead of older one (php 5.4.16).

Cryptor error still shows; reverting changes from commits for Cryptor, openssl-cryptor, and hSecurity.php "fixes" the compatibility issue.

One way to test this is to get portable xampp (1.8.x comes with some php 5.4.x version) if you have windows machine (or virtual), and check against it. Will continue with testing, could be some config option.

**Comment by dev-101** [comment]
Figured it, related to older openssl library, and should affect versions which are not updated, hopefully the impact on live servers will be minimal (if any).

**Comment by conejoninja** [comment]
Sorry, I don't understand.
In 5.6 which error shows? this one ?
```php
PHP Fatal error:  Uncaught exception 'Exception' with message 'Cryptor:: - unknown cipher algo aes-256-ctr' in oc-includes\openssl-cryptor\Cryptor.php:51
```

That's because your openssl extension didn't include 'aes-256-ctr' as a cipher algorithm, you could choose any other available, you could get the list of available cipher algos with 

```php
$algos = openssl_get_cipher_methods(true);
var_dump($algos);
```

then, in your config.php you could

```php
define('CIPHER_ALGO', 'whatever-algo-choosen-from-the-list');
```


There are some issues, with this, I don't think that choosing a rangom algo from the list is ok, and leaving this for the admin to choose one is also a bad idea. A constant might be a good compromise, not easy to mess with but still configurable.

With this last change, we'll not be using openssl if the chosen algo isn't available, so no error

**Comment by dev-101** [comment]
Hi Conejo, thanks, just saw your commit, but read this here (it is similar to the test system I was running 5.4):

https://github.com/defuse/php-encryption/issues/277

Basically, it will affect obsolete windows dlls, and linux servers should be fine with this anyway, as at least openssl will be updated (or should be).

Thanks!

**Comment by dev-101** [comment]
Oh, no... PHP 5.6 is ok, of course.

It affects only windows dlls and older openssl libraries that come with it as explained above, I do not expect that this will be an issue for live servers that run on linux (at least).

**Comment by dev-101** [comment]
Thanks for the trouble! It is now working fine :beer:

**Comment by dev-101** [comment]
Just a minor detail:
PHP Notice:  Use of undefined constant CIPHER_ALGO - assumed 'CIPHER_ALGO'

**Comment by conejoninja** [comment]
did you update default-constant.php too ?

**Comment by dev-101** [comment]
Sorry, forgot it :(

**Comment by dev-101** [comment]
but, "just in case" I have modified the code:

>        return (
>			function_exists('openssl_digest') &&
>			defined('CIPHER_ALGO') &&
>			defined('HASH_ALGO') &&
>			function_exists('openssl_encrypt') &&
>			function_exists('openssl_decrypt') &&
>			in_array(CIPHER_ALGO, openssl_get_cipher_methods(true)) &&
>			in_array(HASH_ALGO, openssl_get_md_methods(true))
>		);
